### ISSUE TITLE
Possibility to support diff coverage

### ISSUE THREAD

**Issue by 151812117** [coverlet-coverage/coverlet#1009]
Hi, is there any possibility to support counting coverage of changed code(including the code that is changed or added ) instead of overall code?
Thanks.

**Comment by petli** [comment]
https://danielpalme.github.io/ReportGenerator/ can create graphs showing the evolution of code coverage by keeping track of previous reports and adding to that history for each run. SonarQube can also show coverage on new code as part of its report on the code health.

I'd recommend looking into adding tools like that to your scripts, since what's new code depends a lot on the context and is not the job of measuring the code coverage itself.  E.g. you might want to measure between two releases, or new code added in a feature branch or PR. Scripting that using coverlet and other tools mean that you can tailor it exactly to your needs.

**Comment by MarcoRossignoli** [comment]
I agree with @petli, I think that compare different coverage session or "elaborate the coverage result" is out of scope of basic "coverage generator tool".  
Also because the features of a tool like that has got a lot of possible scenario, ui etc...

**Comment by tonerdo** [comment]
Closing this out since there's no further action left to be taken
