### ISSUE TITLE
How mark a csproj to be ignored on collect code coverage?

### ISSUE THREAD

**Issue by pedrofernandesfilho** [coverlet-coverage/coverlet#1011]
Is there a way to mark in csproj to be ignored in the collection?

Maybe with some csproj entry like
```
     <PropertyGroup>
         <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
     </PropertyGroup>
```

**Comment by tonyhallett** [comment]
Yes.

The correct method is to apply the ExcludeFromCodeCoverage attribute to the assembly, although unfortunately this will not work for .NET Framework as the AttributeUsage does not include Assembly.

The documentation isn't clear that this is possible for all 3 drivers, it only mentions it for the global tool and MSBuild integration

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#excluding-from-coverage
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage

> You can ignore a method an entire class or assembly from code coverage by creating and applying the ExcludeFromCodeCoverage attribute present in the System.Diagnostics.CodeAnalysis namespace.

`
<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage"></AssemblyAttribute>
`

If you are interested all 3 drivers quickly call into
https://github.com/coverlet-coverage/coverlet/blob/b63ab2adf7970fe074232622cb58ae1928aa7717/src/coverlet.core/Coverage.cs#L104
here you can see the exclude and include filters being used to determine if the module should be instrumented.

Although the code that checks for the ExcludeFromCodeCoverage attribute on the assembly is in the Instrumenter
https://github.com/coverlet-coverage/coverlet/blob/b63ab2adf7970fe074232622cb58ae1928aa7717/src/coverlet.core/Instrumentation/Instrumenter.cs#L233

I think that the exclusion code for the assembly attribute should change to be a name match rather than a full name match as per type and method matching - 
https://github.com/coverlet-coverage/coverlet/blob/5cb26b13e9133c785488234b19f59fc68d8a1eef/src/coverlet.core/Instrumentation/Instrumenter.cs#L76

This way a .Net Framework project can opt out of code coverage in the same manner.
@MarcoRossignoli what do you think ? The assembly attribute commit https://github.com/coverlet-coverage/coverlet/commit/83c47b8dd4abd820f573aa4b4feff36c638eedcc

**Comment by MarcoRossignoli** [comment]
All three drivers supports filters, so you can pass it(exclude filter) to exclude an assembly from coverage, for instance with runsettings for collectors driver:

`<Exclude>[coverlet.*.tests?]*,[*]Coverlet.Core*</Exclude>`

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings

**Comment by MarcoRossignoli** [comment]
> I think that the exclusion code for the assembly attribute should change to be a name match rather than a full name match as per type and method matching -

It should work as is because `nameof` produces the name https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

**Comment by MarcoRossignoli** [comment]
Anyway I think there is a bug for the assembly level exclusion attribute as you pointed out @tonyhallett can you file a new issue for that?

**Comment by tonyhallett** [comment]
> > I think that the exclusion code for the assembly attribute should change to be a name match rather than a full name match as per type and method matching -
> 
> It should work as is because `nameof` produces the name https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

Sorry wasn't referring to the nameof. Should have linked to IsExcludeAttribute which Name checks.

**Comment by tonyhallett** [comment]
> Anyway I think there is a bug for the assembly level exclusion attribute as you pointed out @tonyhallett, can you file a new issue for that?
> https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/Instrumenter.cs#L233 here we should check only name.
> Thanks for reporting this.

If I don't get the chance tomorrow I will make a pull request Monday.

**Comment by pedrofernandesfilho** [comment]
@tonyhallett, thanks by explanation about Assembly Attribute. It worked for me.

**Comment by MarcoRossignoli** [comment]
I'm going to close this as solved.

Feel free to reopen if needed.
