### ISSUE TITLE
Coverlet is displaying the coverage as zero.

### ISSUE THREAD

**Issue by AbedhBabu** [coverlet-coverage/coverlet#1021]
We are using Coverlet to find the code coverage of our application. The UI automation tests are executed via an external tool called Rapise. After execution from TeamCity, the coverage is displaying as zero.

https://www.inflectra.com/Rapise/

Rapise is a tool used to automate Desktop/Windows applications.
SesVSUnit.dll is used to integrate the Rapise test suite with Visual Studio and from Visual Studio the test suites are triggered using Rapise.TestExecute() command.
Xunit is the test caller project.

Please note - we are able to get the coverage of unit tests and integration tests.

**Comment by MarcoRossignoli** [comment]
Can you elaborate more?Can you write the command line command you're using?

**Comment by Adityanr** [comment]
These are the commands we have used @AbedhBabu @MarcoRossignoli 👍 

1) Using Dotnet Test with Coverlet output: "C:\Program Files\dotnet\dotnet.exe" test UISDKStyle.csproj --configuration Release --no-build --verbosity Normal /property:CollectCoverage=True /property:CoverletOutput=UISDKStyle.opencover.xml /property:CoverletOutputFormat=opencover

2) Using Coverlet.exe directly: C:\Users\abedh\.dotnet\tools\coverlet.exe UISDKStyle.dll --target dotnet --targetargs "test UISDKStyle.csproj --no-build --verbosity normal" --output UISDKStyle.opencover.xml --format opencover'

UISDKStyle: This is a UI Automation test SDK style project whose tests are run through an external tool called Rapise.

**Comment by daveMueller** [comment]
Sorry just to make it more clear. Your output ```UISDKStyle.opencover.xml``` doesn't have any coverage data or is it only teamcity that doesn't display the coverage?

**Comment by AbedhBabu** [comment]
Hi Dave, after the test execution, the UISDKStyle.opencover.xml is not having any coverage data.

**Comment by daveMueller** [comment]
OK so you basically want to know how much of your UI Code is covered by the Rapise tests? Can I ask what kind of UI it is, WPF, Forms, Web or some mobile?
I personally never tried to use coverlet on UI code thus I really  don't know if those assemblies are instrumented and I have to give it a try.

**Comment by AbedhBabu** [comment]
We are using Win Forms.

**Comment by daveMueller** [comment]
Sorry for the late response but it took some time to set a project up that is comparable to your scenario. Instead of Rapise I used Appium with the WinAppDriver. You can find my project here (https://github.com/daveMueller/CoverletWinFormsUiAutomationTests).

While setting this up i stumbled across a recent change in coverlet which is documented here (https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage-for-integration-tests-and-end-to-end-tests)

You can check the powershell file in my repo to see how I'm using coverlet. However it works better than I had expected.

![image](https://user-images.githubusercontent.com/19378678/103389689-ab464080-4b10-11eb-95c7-458707e785ea.png)

![image](https://user-images.githubusercontent.com/19378678/103389712-cc0e9600-4b10-11eb-8277-acba7b51adb4.png)

And even the generated UI Code is covered.

![image](https://user-images.githubusercontent.com/19378678/103389726-ef394580-4b10-11eb-918f-e006cfa6d3d1.png)


**There is one issue**. I think this feature isn't released yet because the PR was just merged recently (https://github.com/coverlet-coverage/coverlet/pull/991). @MarcoRossignoli is there already a release with this PR?

In my test repo I compiled it myself but to try it with Rapise you could just grab the coverlet version in my repo or compile current master by yourself.

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli is there already a release with this PR?

No will be release on `3.0.0`  https://github.com/coverlet-coverage/coverlet/pull/1030 for now we can use the nightly build https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
