### ISSUE TITLE
Support deterministic reports

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#1075]
Follow up https://github.com/danielpalme/ReportGenerator/issues/405

we could add a flag `--deterministc-report`  and in case we're in a deterministic build use deterministic path instead of reconstruct the actual one.

- [x] Cobertura (https://github.com/coverlet-coverage/coverlet/pull/1113)
- [ ] Lcov
- [ ] OpenCover
- [ ] TeamCity

cc: @clairernovotny @danielpalme

**Comment by pinkfloydx33** [comment]
Any idea if/when OpenCover will get support?

**Comment by MarcoRossignoli** [comment]
We don't have any plan for the moment, the interest looks not so high, if you want you can take it and I'll review it.

**Comment by pinkfloydx33** [comment]
I'll have to take a look... We don't *really* need it, we just have an unfortunate setup. 

We need Cobertura reports for Azure Devops. We also need OpenCover for Sonar Cloud which doesn't support Cobertura format. We want to migrate our builds/reports to fully deterministic; we've been purposely overriding/disabling determinism in CI test runs due to now fixed issues with ADO+report-generator. Up until now we've been generating both formats, but of course that fails with the deterministic reports enabled since OpenCover doesn't support the flag. 

I haven't found a tool that can turn Cobertura reports into OpenCover, but report-generator can supposedly output lcov format which I think Sonar can accept. That might be a viable option for us and likely less effort than trying to add support here.

**Comment by MarcoRossignoli** [comment]
> I haven't found a tool that can turn Cobertura reports into OpenCover, but report-generator can supposedly output lcov format which I think Sonar can accept. That might be a viable option for us and likely less effort than trying to add support here.

@danielpalme can report generator convert Cobertura to OpenCover?

**Comment by danielpalme** [comment]
> @danielpalme can report generator convert Cobertura to OpenCover?

No, OpenCover is not supported as output format (only Cobertura, lcov and Clover).

**Comment by petli** [comment]
@pinkfloydx33 ReportGenerator can convert to the generic SonarQube coverage format, maybe that will help you?

**Comment by pinkfloydx33** [comment]
Yeah I noticed that too. The generic format is somewhat limited I think. We already use it to report additional linting issues for our React apps so it's at least not foreign to us. I'd have to check if there's any implications in using that format over OpenCover wrt what Sonar displays/can report on for coverage purposes. 

Generic format or lcov, I'm still going to have to update our CI processes to stop generating multiple formats directly, add a conversion step and then tweak the sonar parameters. Not a big deal, but would've preferred OC supported deterministic reports.

Is there any reason OC can't or that makes it difficult? Maybe I _will_ look into offering a PR (ya know... If I ever get some time to myself 😄)

**Comment by danielpalme** [comment]
[OpenCover](https://github.com/OpenCover/opencover) is no longer maintained.

**Comment by dhduvall** [comment]
FWIW, a discussion on [Sonar's Discourse](https://community.sonarsource.com/t/sourcelink-breaks-coverage-report-generation).
