### ISSUE TITLE
Sync nuget and github release versions

### ISSUE THREAD

**Issue by viceice** [coverlet-coverage/coverlet#1122]
Is it possible to sync the github release and the nuget release version?

**Use case**
[renovate](/renovatebot/renovate) is using the github releaes to fetch changelogs for automated dependecy updates.
So currently it can't match a github release to the nuget package version because the version differences.

**Comment by MarcoRossignoli** [comment]
Unfortunately we cannot do that, in origin coverlet was released with 3 different version, one version for every driver:

.NET Tool
msbuild integration
collectors integrations

So historically we released 3 different nuget package version with the same "core" engine. For that reason the github version report the "core" engine version.
Since version `3.0.0` we decided to align all versions and document the drift between features. But engine version is at `5.6.3` and packages to `3.0.3` so will be confusing more that today maybe 😅

**Comment by viceice** [comment]
Maybe do a major bump on all versions to v6 to match?
