### ISSUE TITLE
Please provide option to stop generating directories with random GUID

### ISSUE THREAD

**Issue by lloydjatkinson** [coverlet-coverage/coverlet#1166]
I am trying out Coverlet but unfortunately it does not seem suitable for CI/CD pipelines because it puts the generated HTML report, SVG badges etc. in a directory that is a randomly named GUID. This means that, among other things, I cannot make a repositories README file display the badges showing the coverage values as the path will be unpredictable.

**Comment by petli** [comment]
This is not something that Coverlet can control, unfortunately, but an issue with the underlying vstest platform. #500 discusses this extensively, and the issue is reported at https://github.com/microsoft/vstest/issues/2378

The best way is to look at coverlet as a part of a toolchain, where it produces the underlying report files, and then generate badges, HTML reports etc from them with a dedicated tool such as https://github.com/danielpalme/ReportGenerator

A CI/CD pipeline can combine the tools in a script, or as separate build steps.

**Comment by Malivil** [comment]
Can't you use the "/p:CoverletOutput" option?

**Comment by petli** [comment]
@Malivil: That option unfortunately only works for the msbuild driver, not for the vstest driver. The vstest driver is recommended to use over the msbuild driver, since the latter have an architectural restriction that means it may not always reliably collect all the coverage data for larger projects or in CI environments.
