### ISSUE TITLE
Enhance threshold specification

### ISSUE THREAD

**Issue by jchesshir** [coverlet-coverage/coverlet#1174]
I'm looking for a quick way to set up my build so that it forces developers to unit test their code by failing the build if a certain unit testing threshold is not reached.  

I've already seen the feature of [specifying a threshold through MSBuild arguments](https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#threshold).  However, I believe that specifying a hard coded number like this is only ideal after a team's unit/integration code coverage has been established.  Even then, almost any value can, IMHO, allow the team to get complacent about their coverage and stop striving to do their very best at keeping the coverage percentage as high as possible.

There are a couple of other ways I'd like to be able to have the build fail:

1. Require equal or better numbers than the latest build.  This would be ideal both for a team that is wanting to continue pushing their testing threshold to the next level AND for a team with an established code base that has no unit testing.  It would keep the former team on their toes, even if they are removing old untested code and driving their existing percentage well above the currently accepted threshold.  It would keep the latter team challenged, but would not put undue pressure on targeting legacy code for new automated tests.
2. Require a threshold on recently added and edited code.  This would be an ideal compromise for jump starting a new team's coverage.  If you require, say, 90% for code checked in within the last month, then that would force the team to get started with unit testing by targeting the latest new and edited code, and thus the code most vulnerable to new defects, while ignoring the legacy code that has already been tested in Alpha, Beta, and Production environments.

Is there anything existing in coverlet, or any simple setup I could do, that would achieve something of this nature?

**Comment by petli** [comment]
In both cases I think you should look beyond coverlet itself and see what you can achieve with coverlet together with the build system you use. Ultimately, it is only that system that really knows what's the coverage was in the previous build and what's new code since then (or new code in a PR).

If you can get the build system to store the coverage percentage and make it accessible as a build variable you could achieve alternative 1 by passing that number into the coverlet parameters.

For alternative 2, Sonarqube can check coverage on new code and fail a build (albeit at a price in build times), if you would be able to introduce that system into your build infrastructure.

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
