### ISSUE TITLE
How to exclude test assemblies

### ISSUE THREAD

**Issue by illuzi0n** [coverlet-coverage/coverlet#1179]
Shouldn't test assemblies be excluded by default according to #618 or did something change?

In any case, I tried to exclude test assemblies by setting the `IncludeTestAssembly` flag to false but some test assemblies still appear in the code coverage report. What may be the issue?

Here is the .runsettings file:

```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura,opencover</Format>          
          <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,TestSDKAutoGeneratedCode</ExcludeByAttribute>
          <IncludeTestAssembly>false</IncludeTestAssembly>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

The command I'm using is `dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings`

**Comment by MarcoRossignoli** [comment]
It's excluded by design and you should be able to check inside VSTest logging file generated using https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

**Comment by MarcoRossignoli** [comment]
I mean that by design test assembly is not included in coverage, which version are you using?

**Comment by JohnLudlow** [comment]
@MarcoRossignoli I'd appreciate some more info on this. If you need more info from me, I can probably provide something. I could probably come up with a reproducing sample if that would help - would you like me to attach that here or onto a new issue?

Thanks

**Comment by MarcoRossignoli** [comment]
Yes would be great have a repro or as I said above the logs for the run using `--diag:log.txt` but keep in mind that logs could contains sensitive data and so if you don't want to disclosure is better a repro

**Comment by JohnLudlow** [comment]
@MarcoRossignoli Apologies for the delay here. I tried to make a repro sample, and didn't get the same behaviour.

Our production code is a mix of .NET Framework and .NET Core, and I think one test assembly was being run as a .NET Framework test with vstest.console but it was a .NET Core test so that might have confused things. Also, it's possible that the Azure DevOps plugins pass different defaults than the tools do locally, so I'm working on an MSBuild proj for the pipeline to call.

I'll let you know if I run into more issues as I progress

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
