### ISSUE TITLE
Unable to save new values for Color Codes and change default Report location

### ISSUE THREAD

**Issue by MeiPorulSeeker** [coverlet-coverage/coverlet#1190]
Hi Team,

I am using VS 2019 Enterprise. I installed Run Coverlet Report VS extension, Report Generator and the required Nuget packages in my project as a part of Code Coverage integration. 

Everything works. But I find 3 issues. 

1) After changing the Highlighting Color for various parameters in Run Coverage Report/Options menu in VS, I see that the highlight color gets applied to code editor. But after I reopen Visual Studio, all colors are reset to default. 

2) I am unable to change the default location of the generated report. 

3) The color that is highlighted in the Code Editor clears when I reopen Visual Studio (different from Point 1)

Please let me know if the above are possible.

**Comment by daveMueller** [comment]
Hi @MeiPorulSeeker,

this is not the repository of the VS extension and AFAIK nobody of the team here is maintaining the extension. You should ask your questions in the extensions repository ([https://github.com/the-dext/RunCoverletReport](https://github.com/the-dext/RunCoverletReport)).

I've seen that the extension is using the msbuild driver by default and there it is generally possible to specify the output location ([https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverage-output](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverage-output)).

But we can't provide you with the insights of the extension because we are not maintaining it.

**Comment by MarcoRossignoli** [comment]
Yes we don't maintain VS extension. Pls follow @daveMueller links.
