### ISSUE TITLE
Split transformation and execution

### ISSUE THREAD

**Issue by iskiselev** [coverlet-coverage/coverlet#1195]
We try to use coverlet to get code coverage metrics from e2e tests. In CI, we have separate jobs that build our product (which has access to all sources) that publishes build result and second job, that consume build artifacts and execute e2e test.
Is there any easy way or potential roadblocks to add options in coverlet console to split binaries transformation and code coverage collection though execution?
Can we work to implement this option as PR?

**Comment by MarcoRossignoli** [comment]
If you have E2E test you can use for now coverlet .NET Tool https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage-for-integration-tests-and-end-to-end-tests

The only drawback is that today(we want to improve here) you need to be sure to close process in a gracefully way because coverlet collect hits during process exits.

**Comment by MarcoRossignoli** [comment]
This is a sample I did https://github.com/coverlet-coverage/coverlet/issues/781#issuecomment-691442083

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
