### ISSUE TITLE
Exclude does not work on referenced assemblies

### ISSUE THREAD

**Issue by alps1980** [coverlet-coverage/coverlet#1217]
I have a .Net core 3.1 version c# based project and i have configured coverlet to give me the code coverage report.

I use below command to run the tool.

dotnet test MyProject.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute="Obsolete" /p:Exclude="[MyProjectUnitTests.]*" /p:Exclude="[MyProject2.]*" /p:ExcludeByFile="MyProject2.dll*"

I have added (assembly)dll reference "MyProject2" to the project and i want to exclude everything from that assembly to be shown in code coverage report. And all the code in that assembly falls under namespace MyProject2.* but Exclude argument still doesnt exclude coverage for that assembly in the report. I even tried with ExcludeByFile parameter with dll name but it still doesnt exclude that assembly from the report. 

How can i write the command to exclude the referenced assembly from the report?

**Comment by daveMueller** [comment]
`ExcludeByFile` only excludes source files so you don't need to specify this. The filter syntax is `/p:Exclude=[Assembly-Filter]Type-Filter` and I think the `Type-Filter` part is mandatory. Thus you might should add a wildcard there. Also if your assembly name continues after the dot you should also add a wildcard there. If not remove the dot because I think only assembly names without extension are compared.

```powershell
/p:Exclude="[MyProject2.*]*"
# or
/p:Exclude="[MyProject2]*"
```
