### ISSUE TITLE
Problem with coverage after upgrading to .net5[WindowsDesktop app]

### ISSUE THREAD

**Issue by abdelrahman-alfar** [coverlet-coverage/coverlet#1221]
C:\Users\bamboo\.nuget\packages\coverlet.msbuild\3.1.0\build\coverlet.msbuild.targets(39,5): warning : [coverlet] Unable to instrument module: XXX because : AssemblyResolutionException for 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line
  
  After upgrading to .net5 we have a problem with coverage for one of our projects, the rest of the projects are correctly detected
  
  I tried both suggestions but nothing happens keep receiving the above error

**Comment by abdelrahman-alfar** [comment]
any help here? its affecting our team performance at SAP

**Comment by abdelrahman-alfar** [comment]
@daveMueller could you assist here?

**Comment by daveMueller** [comment]
Could you try the solutions described in #1102? For me it feels like the same issue.

**Comment by abdelrahman-alfar** [comment]
Hi @daveMueller I tried publish but still 
whats weird that I have 4 projects (one of them is the main file) all published to the same directory and they dont complain about this framework

I attached the logs from our CI bamboo tool
[plan-286097710-SQI-39.log](https://github.com/coverlet-coverage/coverlet/files/7226621/plan-286097710-SQI-39.log)

please let me know if you have other ideas/suggestions

**Comment by abdelrahman-alfar** [comment]
@daveMueller did you have the chance to check it?

**Comment by MarcoRossignoli** [comment]
Hi @abdelrahman-alfar and thx a lot @daveMueller for the help here,

> After upgrading to .net5 we have a problem with coverage for one of our projects, the rest of the projects are correctly detected

Have you moved from .NET 4.x or from .NET 3.x?

> TryWithCustomResolverOnDotNetCore for PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Looking at log this is the main error coverlet during static instrumentation is not able to find `PresentationFramework` dll and so fails to instrument lib that depends on it(I think it's your missing project).

How do you build the project?
Can you verify if in your output folder the lib `PresentationFramework` is present(I think no)?
Are you able to create a repo, I think that do a test with a plain .NET 5 Wpf app is enough.


In past we had similar issue for asp.net, unfortunately coverlet needs to load some deps during instrumentation(Cecil works in this way) and sometimes framework/msbuild(wpf, asp.net, compilers etc...) change the output layout, sometimes they copy lib on out folder sometimes use the "machine wide" installation. I in .NET 5.0 on wpf we have the same scenario I think we'll need to add a new extension to our resolver

https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs#L73 -> https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs#L229

And try to load from local `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App`

Another good addition to avoid to block user would be add a new option to let user to specify additional probing directory so in case of loading error as a "workaround" the user can specify where to search libs.

**Comment by MarcoRossignoli** [comment]
I'll keep this one open, we need to improve here.

**Comment by marbel82** [comment]
@abdelrahman-alfar Can you tell me from where you copy the files? Could you show me your post-build?


I have the same problem.

`
Unable to instrument module: c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\Module.dll because : AssemblyResolutionException for 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line
`

but when I copy PresentationFramework.dll
from `c:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\PresentationFramework.dll`
to `c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\`

coverlet print:

`
Unable to instrument module: c:\Komlogo\KomKOD\GIT\app\KomKODSources\Tests\KClasses_UnitTest\bin\Debug\net5.0-windows\KClasses.dll because : Failed to resolve System.Windows.Threading.DispatcherPriority
`

And now I don't know what to do about it.

(I come here from https://github.com/FortuneN/FineCodeCoverage/issues/188 because I use FineCodeCoverage)

**Comment by marbel82** [comment]
@abdelrahman-alfar Can you tell me from where you copy the files? Could you show me your post-build?
<br/>

I have the same problem.

> Unable to instrument module: c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\Module.dll because : AssemblyResolutionException for 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line

but when I copy PresentationFramework.dll
from `c:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\PresentationFramework.dll`
to `c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\`

coverlet print:

> Unable to instrument module: c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\Module.dll because : Failed to resolve System.Windows.Threading.DispatcherPriority

And now I don't know what to do about it.

(I come here from https://github.com/FortuneN/FineCodeCoverage/issues/188 because I use FineCodeCoverage)

**Comment by marbel82** [comment]
I charged my brain ;)  and I remembered that `System.Windows.Threading.DispatcherPriority` is inside some assembly.

I just add `WindowsBase.dll` to `...\bin\Debug\net5.0-windows\` and **Fine Code Coverage** working again!

**Comment by 304NotModified** [comment]
This is the same issue : https://github.com/coverlet-coverage/coverlet/issues/1231

Copying the dll from the **refs** folder helped multiple users. See that issue for some scripts

**Comment by MarcoRossignoli** [comment]
@304NotModified outcome is the same but in this case is slightly different...here we can fix adding well known folders like `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.0` but not in all cases we have this info.

**Comment by lg2de** [comment]
In PR #1449 I tried to fix the problem close to the idea mentioned by @MarcoRossignoli.
Would be great to get some feedback whether this fixes (also) your problem(s).
