### ISSUE TITLE
Zero coverage collection specifically during a CI build

### ISSUE THREAD

**Issue by atifaziz** [coverlet-coverage/coverlet#1259]
I've been updating my project, [CSharpMinifier](https://github.com/atifaziz/CSharpMinifier), to bring it up to date with the .NET 6 SDK as well as its dependencies. As part of that, I've been also [fixing the code coverage collection](https://github.com/atifaziz/CSharpMinifier/pull/27) by using the data collector instead of the MSBuild integration (which was misreporting coverage with `NaN` percentages).

Everything is working locally, as can be seen by the following text summary generated by [ReportGenerator](https://github.com/danielpalme/ReportGenerator):

    Summary
      Generated on: 13/11/2021 - 14:42:18
      Parser: MultiReportParser (15x CoberturaParser)
      Assemblies: 1
      Classes: 14
      Files: 11
      Line coverage: 96.9%
      Covered lines: 1065
      Uncovered lines: 33
      Coverable lines: 1098
      Total lines: 2209

    CSharpMinifier                            96.9%
      CSharpMinifier.CSharpString             99.3%
      CSharpMinifier.Internals.JsonString     96.4%
      CSharpMinifier.MinificationOptions      96.0%
      CSharpMinifier.Minifier                 98.8%
      CSharpMinifier.Position                 82.3%
      CSharpMinifier.Region                   75.0%
      CSharpMinifier.Scanner                  99.7%
      CSharpMinifier.StringExtensions        100.0%
      CSharpMinifier.StringValueParseResult   59.3%
      CSharpMinifier.SubstringPool           100.0%
      CSharpMinifier.SyntaxErrorException     33.3%
      CSharpMinifier.Token                    33.3%
      CSharpMinifier.TokenExtensions         100.0%
      CSharpMinifier.TokenKindExtensions     100.0%

However, on CI builds (using AppVeyor), I am getting zero coverage:

    Summary
      Generated on: 11/13/2021 - 1:39:02 PM
      Parser: MultiReportParser (6x CoberturaParser)
      Assemblies: 0
      Classes: 0
      Files: 0
      Line coverage: 
      Covered lines: 0
      Uncovered lines: 0
      Coverable lines: 0
      Total lines: 0
    No assemblies have been covered.

I have Codecov setup to report on uploaded coverage data and [it's showing a blank](https://app.codecov.io/gh/atifaziz/CSharpMinifier/commit/f4a4bfebbb3a4268301054ef108ed8a95e92ea2c). When I check the [coverage XML files uploaded to Codecov, they are indeed empty](https://api.codecov.io/upload/gh/atifaziz/CSharpMinifier/download?path=v4/raw/2021-11-13/2F167F9C8123F0D96D96ADCCBC465497/f4a4bfebbb3a4268301054ef108ed8a95e92ea2c/14bd1def-2f94-48f4-8467-205e775b4b8e.txt).

I have also [added diagnostics logging and uploaded the files as artifacts](https://ci.appveyor.com/project/raboof/csharpminifier/builds/41518796/job/hvorpax0hh6jw547/artifacts) but cannot find anything unusual or an error in them.

I have scanned the issues in this repo and went over the [troubleshooting page](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md) to try and solve the problem on my own, but now opening this issue having reached a roadblock. Hope it's not some stupid mistake on my part. Let me know how I can help with more data and input to troubleshoot this issue.

**Comment by daveMueller** [comment]
Hi @atifaziz, I just peeked into your logs and what I'm seeing is 

```
[coverlet]Unable to instrument module: C:\projects\csharpminifier\tests\bin\Debug\net6.0\CSharpMinifier.dll, pdb without local source files, [C:\projects\csharpminifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\B77E55610579DD0B6DB888B18418EAF4A3C0D1D5\Nullable\1.3.0\Nullable\AllowNullAttribute.cs]
```

Basically the pdb of your assembly has references to the source files. Coverlet is searching for these files and in your case it doesn't find `AllowNullAttribute.cs`.  This source file seems to be something from the `nullable.1.3.0.nupkg` but I really don't know why this package delivers source files. 

Nevertheless you have to make sure that these files are really at the location that your assembly references them while `coverlet` calculates coverage. Maybe AppVeyor cleans the `obj` directory after build or something like that. Unfortunately I couldn't reproduce it locally because there all source files are found.

**Comment by atifaziz** [comment]
@daveMueller Thanks for investigating and spotting that issue. I'm afraid, I don't think it accounts for the difference between the local and CI run. I see the same error/message in the log files when I run `test.cmd`/`test.sh` locally yet that doesn't seem to be preventing coverage from being reported correctly.

> Unfortunately I couldn't reproduce it locally because there all source files are found.

That's my case too, but do you also see the problem logged when running `test.cmd`/`test.sh` locally from branch [`fix/coverage-collection`](https://github.com/atifaziz/CSharpMinifier/tree/fix/coverage-collection) and atifaziz/CSharpMinifier@f4a4bfebbb3a4268301054ef108ed8a95e92ea2c?

**Comment by daveMueller** [comment]
OK I found a weird way to reproduce it and it really has to do with `nullable.1.3.0.nupkg`. When the directory with the `Nullable` source files is empty I get exactly the same error locally ([log.datacollector.21-11-14_22-09-27_96765_5.txt](https://github.com/coverlet-coverage/coverlet/files/7534679/log.datacollector.21-11-14_22-09-27_96765_5.txt))

So now why are those source files missing after the assembly was build? While observing this I saw that in my case this only happens every 2nd time when running `dotnet build`. So when running `dotnet build` the 2nd time and then started coverage calculation the calculation failed because of the error in the log. I know this sounds weird so I attached a gif that shows the observed behavior.

![Animation](https://user-images.githubusercontent.com/19378678/141698507-17d30fc5-8624-45e7-a407-e3a77c9f9e8b.gif)

I really don't have a clue why this is happening. Maybe you can also try to reproduce this locally and then we could open a issue at the `Nullable` repo. 

I somehow think this has something to do with the different targetframeworks and maybe the build order of the test projects but this is just some wild speculation. For me I could reproduce it every 2nd time running `dotnet build`. So maybe you can work around this by setting up your pipeline in a way that the tests are executed right after the first build.
Sorry for not being of much help here.

**Comment by atifaziz** [comment]
Hey @daveMueller, just thought I'd share some some of my findings so far in case it can help in the future even though it's not related to coverlet. It seems that _incremental cleaning_ is the culprit here. I found the following in the build logs for second runs:

    IncrementalClean:
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\AllowNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\DisallowNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\DoesNotReturnAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\DoesNotReturnIfAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\MaybeNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\MaybeNullWhenAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\MemberNotNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\MemberNotNullWhenAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\NotNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\NotNullIfNotNullAttribute.cs".
        Deleting file "A:\CSharpMinifier\src\CSharpMinifier\obj\Debug\netstandard2.0\NuGet\2FAA44F34CC261533864249AA4CA67060BF904CA\Nullable\1.3.0\Nullable\NotNullWhenAttribute.cs".

I think I might be running into dotnet/msbuild#1054 although I still haven't found a solution based on what I've read in the issue's thread.

**Comment by atifaziz** [comment]
So [disabling incremental cleaning](https://github.com/atifaziz/CSharpMinifier/commit/96200dd7349fea35b703cf33cd5133793ff3c05b) did the trick for me! [Coverage is not being reported during a CI build too](https://ci.appveyor.com/project/raboof/csharpminifier/builds/41542853/job/ovy98c7hsej7xhrn#L237)! 🎉

@daveMueller Thanks again for sharing your findings, which provided hints and helped me to find the real culprit and solution!
