### ISSUE TITLE
error NU1202: Package coverlet.console 3.1.2 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package coverlet.console 3.1.2 supports: net5.0 (.NETCoreApp,Version=v5.0) / any

### ISSUE THREAD

**Issue by AraHaan** [coverlet-coverage/coverlet#1321]
Cant install coverlet.console into .NET 6 projects.

**Comment by AraHaan** [comment]
After so long of using it I tried to do it into a project :smile:

**Comment by madhusameena** [comment]
Hi


> Coverlet.console is a .net tool you don't have to install "in a project" but machine wide.
> 
> ```
> dotnet tool install --global coverlet.console
> ```

If I want to use this as package in runner instead of global installation like opencover or dotcover 
Is it possible to use it for dotnet 6 ?

**Comment by AraHaan** [comment]
cant you install it as a local tool in your tool manifest file in your repository?

**Comment by MarcoRossignoli** [comment]
@madhusameena it's not clear what you mean, but like @AraHaan said you can install inside your repo on the fly and use it as a runner.
Coverlet .NET Tool is meant to be used as a tools and not referenced inside a project.

I'm going to close this issue because solved I think, but feel free to reopen if needed.
