### ISSUE TITLE
Coverlet Cannot Cover Module Using MVVM Toolkit (CommunityToolkit/dotnet)

### ISSUE THREAD

**Issue by will-jj** [coverlet-coverage/coverlet#1345]
With a module containing code generated by the MVVM Toolkit coverage information from Coverlet will not be created.

I have a simple repro repo here:  https://github.com/will-jj/MVVM-Coverage
Additionally the following log information may provide further insight into the cause of the issue:

```
[coverlet] Unable to instrument module: C:\x\CoverageIssue\CoverageIssue.Tests\bin\Debug\net6.0-windows\CoverageIssue.dll, pdb without local source files, [C:\x\CoverageIssue\CoverageIssue\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CoverageIssue.ViewModelUsesObservableProperty.cs]
```

The original issue was opened here: https://github.com/CommunityToolkit/dotnet/issues/264

**Comment by petli** [comment]
Hi, this is a known issue, where Coverlet needs a hint from the code generator that the source code is generated. That hint is that the file ends in `.g.cs`, rather than plain `.cs`. If MVVM Toolkit can change that in the filenames being generated Coverlet will handle it correctly.

#1164 explains more what's causing this.

**Comment by will-jj** [comment]
Thank you for the information, & apologies for overlooking the information that was available prior to opening this issue. 

The change to `.g.cs` has been proposed in the following PR : https://github.com/CommunityToolkit/dotnet/pull/284

**Comment by petli** [comment]
No problems, glad it could be solved quickly for you!
