### ISSUE TITLE
TestCase ignored in coverage

### ISSUE THREAD

**Issue by creasoft-dag** [coverlet-coverage/coverlet#1446]
Hi,

when i only use [TestCase] attributes then the tests are ignored in the coverage.
If i add [Test] attributes the coverage is working as expected.

``` 
    [Test]
    [TestCase("de")]
    [TestCase("en")]
    [TestCase("xy")]
    [TestCase(null)]
    public async Task MyTest(string language)
    {
      // Arrange
      ...

      // Act
      ...

      // Assert
      using (new AssertionScope())
      {
        ...
      }
    }
```

Best regards,
Daniel

**Comment by creasoft-dag** [comment]
Update: [Test] Attribute only worked für dotCover (which we use local) but not for coverlet (which runs on our CI server). So all the [TestCase] tests are ignored in our coverlet analysis.

**Comment by daveMueller** [comment]
Could you elaborate this a bit more or even better would be small repro so we can exactly see what the issue is.
The instrumentation for the coverage is done on the assembly under test and not the test assembly itself, thus I don't really see how the `[Test]` attribute should have any influence on this.
Or do you want the test assembly to be included in the coverage report? Therefore `coverlet` has a setting `IncludeTestAssembly` which is also discussed here #618.

**Comment by creasoft-dag** [comment]
nvm I just forgot to add the coverlet dependency for some projects - thanks for your help
