### ISSUE TITLE
Exclude with filter doesn't work

### ISSUE THREAD

**Issue by AndreuCodina** [coverlet-coverage/coverlet#1451]
I can't exclude projects. I have the test project `CoverletDemoTests` and two references: `CoverletDemoLibraryOne` and `CoverletDemoLibraryTwo`. By default both projects are added to the coverage, but I want to exclude `CoverletDemoLibraryTwo`, so I execute the next command:

`dotnet test --collect:"XPlat Code Coverage" --results-directory ./generated/coverage /p:Exclude="[*]CoverletDemoLibraryTwo*"`

But it generates coverage for both projects instead of only for `CoverletDemoLibraryOne`.

You can test it with the next project: https://github.com/AndreuCodina/CoverletDemoSolution
And if you want, you have the file `script.ps1` in the root folder to automate the execution.

**Comment by daveMueller** [comment]
You can't use the `collector` with the parameter `/p:Exclude` because this is a switch for `coverlet.msbuild`. 
For the data collector you need to specify the exclusion in a [runsettings](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings) file like this:

`coverlet.runsettings`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>        
          <Exclude>[*]CoverletDemoLibraryTwo*</Exclude>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```
And then call vstest:
```ps1
dotnet test --collect:"XPlat Code Coverage" --results-directory ./generated/coverage --settings coverlet.runsettings
```

Alternatively you could specify the exclusion with [xml flat](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline) syntax:
```ps1
dotnet test --collect:"XPlat Code Coverage" --results-directory ./generated/coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*]CoverletDemoLibraryTwo*"
```

In both cases your project is excluded properly:
![grafik](https://user-images.githubusercontent.com/19378678/221055297-1465eed6-f5a2-47d6-b787-99ba6d9a0d0d.png)

**Comment by AndreuCodina** [comment]
Oh, ok! Thank you very much Dave :)
