### ISSUE TITLE
Use System.CommandLine instead of McMaster.Extensions.CommandLineUtils

### ISSUE THREAD

**Issue by Bertk** [coverlet-coverage/coverlet#1474]
McMaster.Extensions.CommandLineUtils has a dependency System.ComponentModel.Annotations V5.0.0 and this package is deprecated.

see also https://github.com/natemcmaster/CommandLineUtils/issues/533

**Expected behavior**
No deprecated package is used.

![image](https://github.com/coverlet-coverage/coverlet/assets/2315215/6770a2d0-9346-41b5-afa5-c4e89cd2ff5b)

**Comment by MarcoRossignoli** [comment]
@daveMueller we should move to https://learn.microsoft.com/en-us/dotnet/standard/commandline/

**Comment by Bertk** [comment]
@MarcoRossignoli @daveMueller 
The deprecated flag was removed from **System.ComponentModel.Annotations** V5.0.0
![image](https://github.com/coverlet-coverage/coverlet/assets/2315215/c42454fb-fbc0-4d6d-a6d3-995d2dbd76dd)

**Comment by daveMueller** [comment]
@MarcoRossignoli @petli even though the package isn't deprecated anymore should we still move to `System.CommandLine`? 
The disadvantage is that `System.CommandLine` is still beta since 2 years and not sure if it will ever be officially released. @MarcoRossignoli maybe you got any insides on this?

However `McMaster.Extensions.CommandLineUtils` also is in maintenance mode [https://github.com/natemcmaster/CommandLineUtils#project-origin-and-status](https://github.com/natemcmaster/CommandLineUtils#project-origin-and-status) and doesn't have much active development anymore.

We alread have a PR for `System.CommandLine` here #1486 and I think it might be more futur-proof as it maybe becomes part of the sdk someday.

**Comment by Bertk** [comment]
Please note: _**System.CommandLine 2.0.0-beta4.23307.1**_  is also used from [**dotnet/sdk**](https://github.com/search?q=repo%3Adotnet%2Fsdk%20%20%20system.commandline&type=code)

Microsoft published the documentation here: https://learn.microsoft.com/en-us/dotnet/standard/commandline/

**Comment by MarcoRossignoli** [comment]
Let me get some information but I think it's fine use the preview.

**Comment by MarcoRossignoli** [comment]
@daveMueller I confirm that's good to merge also in preview, feel free to review and let me know if I can merge

**Comment by Bertk** [comment]
#1486 was merged
