### ISSUE TITLE
Hiding and excluding some parameters on the Coverage Code tab (Azure DevOps)

### ISSUE THREAD

**Issue by olegsidokhmetov** [coverlet-coverage/coverlet#1558]
Hello!

I have a question.
Is it possible to hide "Risk Hotspots" in the "Coverage Code" tab (Azure DevOps pipelines)
<img width="549" alt="aVsz3Sxkn3" src="https://github.com/coverlet-coverage/coverlet/assets/51410180/e14095a1-386d-4e31-93ad-9819084bd109">

and also exclude "Converge.Libraries.NuGetUtilities" and "nameWebApi"  from the test results in the "Coverage Code" tab? 
<img width="846" alt="BpeBrhn8sy" src="https://github.com/coverlet-coverage/coverlet/assets/51410180/8ad46bc4-0c76-442a-9778-f3ba1a14e3a8">
<img width="1084" alt="chrome_WhXDM8VEQa" src="https://github.com/coverlet-coverage/coverlet/assets/51410180/aa033e12-4c7f-4f9a-8871-ebc8b44d789b">

May it possible from step unit test in Arguments after parameters `--logger:"console;verbosity=normal" --configuration $(buildConfiguration) --collect:"XPlat Code Coverage /p:Exclude="[nameWebApi.*]*, [NuGet.*]*"
<img width="524" alt="chrome_R6NENmEMZZ" src="https://github.com/coverlet-coverage/coverlet/assets/51410180/938665a0-7832-4d86-92cc-120f4ac950d7">

**Comment by daveMueller** [comment]
Coverlet is only calculating the coverage report. For visualization it seems you are using [reportgenerator](https://github.com/danielpalme/ReportGenerator). The whole html representation including the `Risk Hotspots` tab is created by `reportgenerator` and I don't know if this html report can be customized. Most likely not.
But at least you should be able to exclude "Converge.Libraries.NuGetUtilities" and "nameWebApi" from the coverage report. I see you are using the `collector` version of `coverlet` because of `--collect:"XPlat Code Coverage"` and you try to filter with the `msbuild-coverlet` parameters (`/p:Exclude=...`). This will not work.
If you are using the `collector` you need to define a `runnsettings` file with the filter which is described here: [vstest-docs](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings).
If you are using the `msbuild` version of coverlet you can use the filter as described here: [msbuild-docs](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage)

**Comment by danielpalme** [comment]
Risk hotspots can be disabled. The assemblies can be excluded from the report.

Apply the following two settings (last two lines are relevant):

```yaml
- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    assemblyfilters: '-Converge.Libraries.NuGetUtilities;-*WebApi' 
    customSettings: 'settings:disableRiskHotspots=true'
```
