### ISSUE TITLE
[BUG]The process cannot access the file because it is being used by another process in jenkins

### ISSUE THREAD

**Issue by 162September1996** [coverlet-coverage/coverlet#1593]
C:\Users\user\Downloads>Jenkins>java -jar jenkin.war
The process cannot access the file because it is being used by another process.
![Screenshot 2024-01-18 190202](https://github.com/coverlet-coverage/coverlet/assets/155871058/c4523b41-5b2f-4373-8b89-256e03f85db1)

**Comment by Bertk** [comment]
Hi, I am sorry but this issue is might be related [Jenkins installation](https://www.jenkins.io/doc/book/installing/war-file/) and not to coverlet code coverage tooling. We have also a issue template which should be used. This template defines some necessary information.

I will close the issue because it looks like it is created by a bot.
