### ISSUE TITLE
Version numbers don't match up

### ISSUE THREAD

**Issue by johnradke** [coverlet-coverage/coverlet#570]
Latest release (according to https://github.com/tonerdo/coverlet/releases) was 5.2.0, but the corresponding nuget packages are variously 1.1, 1.6, and 2.7. Can we make the package versions line up with the github release version?

That way there's less confusion whether a new feature has made it into a given nuget package version. Thanks!

**Comment by MarcoRossignoli** [comment]
@tonerdo what do you think?I don't know the history of release number.

**Comment by MarcoRossignoli** [comment]
We cannot use same versions because we have three way to use coverage engine, msbuild, .net tool and vstest collectors and unfortunately not all drivers supports all features so we need to diverge a bit, version you see on release is the version of "engine" that is shared between drivers that diverge in features supported.
