### ISSUE TITLE
IncludeTestAssembly should default to true

### ISSUE THREAD

**Issue by sharwell** [coverlet-coverage/coverlet#618]
I just enabled coverlet on a new repository, and the coverage reports were incomplete. The root cause turned out to be a setting `IncludeTestAssembly`, which confusingly excluded code from the coverage report even though that code was not part of any of the various exclude properties.

Test code is an essential part of a production code base, and should always be included in coverage collection. It's fine to provide a property so it can be disabled, but the property should default to the value users are expected to use.

**Comment by MarcoRossignoli** [comment]
We did this discussion a lot of times

https://github.com/tonerdo/coverlet/issues/372#issuecomment-477626872
https://github.com/tonerdo/coverlet/pull/318#issuecomment-457200404

and also on other issues...

Personally I don't have a strong opinions...I observed that a lot of users expect that test project won't be included in coverage by design, they don't see test project useful to cover but that add noise to results.

> Test code is an essential part of a production code base

I agree, this perfect "accademic" statement makes a lot of sense...btw there is a drift between theory and reality for what I observed.

Make a change now could be a "breaking" in expected result, I mean coverage thresholds will raise and maybe they will lose possible coverage issue.

Said that, we can change flag and defaults and announce a breaking in behaviour, it's doable.

I don't want to be only voice here, I can implement the change but I would like to reach a more large agreement once and for all if possible, so I ask to more "active" users what they think about, also because after vstest integration coverlet is the "xplat coverage tool" and stuff are becoming interesting https://nugettrends.com/packages?months=12&ids=coverlet.msbuild&ids=coverlet.collector&ids=coverlet.console

@tonerdo @petli @ViktorHofer @vagisha-nidhi(vstest) @AArnott and if you want to cc someone else that could help please do. 

OOT I sell always vstest integration like the best way to consume coverlet, due to well know issue https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md

**Comment by sharwell** [comment]
It's been a while so I forgot I was part of the discussion. 🤦‍♂ 

I just filed the issue since I was switching a repository from OpenCover to Coverlet and observed the unexpected lack of coverage in test code.

**Comment by AArnott** [comment]
I would like coverage data on test projects by default, but IMO the % coverage reports should exclude the test projects. If we strive for 90% coverage on the product assembly, getting 98% on the test assembly shouldn't count toward the 90% goal on the product.

**Comment by PureKrome** [comment]
I know i'm late to this party - so I'm trying to understand what people are thinking here.

A test method tests some _product_ assembly/method. Kewl. So why do we want coverage on a test method? The tests are there to verify the product assembly is working great. The coverage is used to make sure the product assembly is tested appropriately.

I don't see why anyone would care if a test method is ... covered? All I could see that this could highlight are some 'orphaned' methods in the test project which are called/used any more?

**Comment by MarcoRossignoli** [comment]
Sam's comment https://github.com/tonerdo/coverlet/pull/318#issuecomment-457223596

**Comment by MarcoRossignoli** [comment]
Seems that exclude test project by default is the expected behavior for the majority.

**Comment by StingyJack** [comment]
@sharwell or @AArnott - can you share the reasoning for why you would want to have coverage reported for something other than how well the unit tests cover the production code?   What would that be useful for?

**Comment by MarcoRossignoli** [comment]
> @sharwell Sam Harwell FTE or @AArnott Andrew Arnott FTE - can you share the reasoning for why you would want to have coverage reported for something other than how well the unit tests cover the production code? What would that be useful for?

I think the idea is that for some reason you're not running that tests you're missing something also if you code coverage looks good.

**Comment by sharwell** [comment]
@StingyJack We've seen cases like this:

```csharp
void VerifyThrowsWillThrowNotSupportedException()
{
  Assert.Throws<NotSupportedException>(() =>
  {
    DoesNotThrow();
    Throws();
  };
}

void DoesNotThrow() => throw new NotSupportedException();

void Throws() => throw new NotSupportedException();
```

In this case, the test passes, but it's not doing what it appears to be doing. When the change is submitted and code coverage is provided for the test methods, it's immediately obvious from the coverage that `Throws()` is not being invoked, which means the test isn't covering the method the user expects it to cover.

**Comment by StingyJack** [comment]
@sharwell - the example is wrong to me if `Throws()` and `DoesNotThrow()` are the functions under test and in the production code, because that should be two separate tests,  And if they are production code I would expect that coverage reports that `Throws()` is not covered as it never gets reached during a test.  If those two functions are in the test code, why are we writing tests for them in the first place when they dont touch production code? And if they arent production code, why would I care if they are covered or not?

You completely lost me with the last paragraph. I'm sure there is some sage advice in there but saying something like code coverage is valuable only when using a of feature git - when I know that it is valuable with or without any other VCS - is creating a rather large mental block for digesting the message.
