### ISSUE TITLE
0 byte coverage.info

### ISSUE THREAD

**Issue by aalmada** [coverlet-coverage/coverlet#714]
I'm trying to upload the coverage report to _coveralls.io_ using _GitHub Actions_. 

I'm using the [coverallsapp/github-action](https://github.com/coverallsapp/github-action/) action which supports the `lcov` report format.

I'm executing the folowing:

`dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:netcoreapp3.0 -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=TestResults/ /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByFile="../NetFabric.Hyperlinq.Interfaces/*.cs"`

The unit tests project `NetFabric.Hyperlinq.UnitTests` uses `xUnit` to test the project `NetFabric.Hyperlinq` which references project `NetFabric.Hyperlinq.Interfaces`.

When I execute the command (in the terminal), the referenced project is included and the report has 0 bytes. Executing again the exact same command, the referenced project is not included and the report has 1MB. Executing again, I get the 0 bytes report...

The project can be found at https://github.com/NetFabric/NetFabric.Hyperlinq/pull/99

**Comment by MarcoRossignoli** [comment]
Hi Antão come back asap. BTW I cloned and I cannot compile with
```
C:\git\coverletissue\NetFabric.Hyperlinq (master -> origin)
λ dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:netcoreapp3.0 -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=TestResults/ /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByFile="../NetFabric.Hyperlinq.Interfaces/*.cs"
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 78,08 ms for C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj.
  Restore completed in 454,73 ms for C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.Interfaces\NetFabric.Hyperlinq.Interfaces.csproj.
  Restore completed in 521,88 ms for C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq\NetFabric.Hyperlinq.csproj.
  Restore completed in 1,65 sec for C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj.
Conversion\AsValueEnumerable\AsValueEnumerable.Enumerable.Tests.cs(42,18): error CS0411: The type arguments for method 'ReadOnlyList.ElementAt<TList, TSource>(TList, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj]
Conversion\AsValueEnumerable\AsValueEnumerable.ReadOnlyCollection.Tests.cs(42,18): error CS0411: The type arguments for method 'ReadOnlyList.ElementAt<TList, TSource>(TList, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj]
Conversion\AsValueEnumerable\AsValueEnumerable.ReadOnlyList.Tests.cs(42,18): error CS0411: The type arguments for method 'ReadOnlyList.ElementAt<TList, TSource>(TList, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [C:\git\coverletissue\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj]
```
Fresh repo

**Comment by MarcoRossignoli** [comment]
You should upgrade coverlet to `2.8.0` or better use collectors https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md the only bad thing is that generated coverage file is not in a stable folder name because vstest put file in `Folder/guid/file.lcov` so you have to move file in a fixed folder for coveralls(or open a issue on that repo for glob pattern support)

Second you have to update a bit the filter...you're using 
```
<PackageReference Include="Nullable" Version="1.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```
This package generates a `NullableAttributes.cs` in your source code, but coverlet skip to instrument assembly if source are not found in local and that file is not reachable, so the correct command line is 
```
dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:netcoreapp3.0 -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=.\TestResults/ /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByFile="../NetFabric.Hyperlinq.Interfaces/*.cs%2c/**/NullableAttributes.cs"
```

**Comment by aalmada** [comment]
@MarcoRossignoli Thank you so much for going into all this trouble.

There's no urgency. Today I won't have time to test all your suggestions.

I'd love to try the collectors. It makes it so much simpler.

**Comment by MarcoRossignoli** [comment]
For collector is the same filter story!

**Comment by idg10** [comment]
This filter:

`/p:ExcludeByFile="../NetFabric.Hyperlinq.Interfaces/*.cs%2c/**/NullableAttributes.cs"`

doesn't seem to work, because before ever inspecting that filter string, `Instrumenter.CanInstrument` will check that every source file for a module is present (with no reference to `ExcludeByFile`). Because of https://github.com/dotnet/sdk/issues/10914 we sometimes get into a situation where the `NullableAttributes.cs` file added by the `Nullable` NuGet package has already been deleted by the time Coverlet runs.

So the upshot is that `Instrumenter.CanInstrument` rejects the entire module because it can see one source file (`NullableAttributes.cs`) is missing, and it never realises that the only missing source file is one we wanted to exclude anyway.

**Comment by MarcoRossignoli** [comment]
Thank's @idg10 understood the issue, at the moment I don't have idea how to solve it.
We have to check if use a less aggressive check works well(check if all files are missing not only one).
I don't know if possible but are you able to create a repro?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to re-open if needed!
