### ISSUE TITLE
Coverage report file duplicated when using --logger option

### ISSUE THREAD

**Issue by tremblaysimon** [coverlet-coverage/coverlet#733]
In my test project, when I run the command:
```
dotnet test --settings coverlet.runsettings --logger "trx;LogFileName=testresults.trx"
```
there are two coverage.opencover.xml file generated. They are identical. Only the path where the file resides are different. There is one in TestResults/a-random-guid/ and another one in TestResults/USERNAME_COMPUTERNAME_generation-date/In/COMPUTERNAME/.

![image](https://user-images.githubusercontent.com/5879940/74684320-9c28ff00-5199-11ea-89f9-5c744be62014.png)

I'm using .NET Core SDK 3.1.101, coverlet.collector 1.2.0 and Microsoft.NET.Test.Sdk 16.5.0.

One thing maybe when I start dotnet test it specifies version 16.3.0 (I don't know if it's normal, I think yes since it the version installed by the SDK): 

```
Outil en ligne de commande d'exécution de tests Microsoft (R), version 16.3.0
Copyright (c) Microsoft Corporation. Tous droits réservés.
```

In the end, I don't know if it's more or less related to vstest than coverlet. 

If I don't use --logger option, it doesn't generate a second code coverage file.

**Comment by MarcoRossignoli** [comment]
Thank's for reporting this, we'll take a look asap.

**Comment by MarcoRossignoli** [comment]
@tremblaysimon I did a test and confirm your results, I think you should open an issue on vstest repo and ask if this behaviour is by design https://github.com/microsoft/vstest
On coverlet we simply send artifacts to message sink and we don't have any control on it https://github.com/tonerdo/coverlet/blob/master/src/coverlet.collector/DataCollection/AttachmentManager.cs#L146

Feel free to close and reference this issue on other repo. We'll re-open if needed.
