### ISSUE TITLE
[F#]Type declarations in F# are shown as not covered

### ISSUE THREAD

**Issue by SteveGilham** [coverlet-coverage/coverlet#76]
This is the same issue as [OpenCover issue #615](https://github.com/OpenCover/opencover/issues/615) -- the compiler generates many functions (such as comparison operations) which show in the IL but not in the source
![615-bis](https://user-images.githubusercontent.com/7460854/39565586-69398f62-4eb0-11e8-8bc3-f584a929a6dc.png)
While I can apply a class-level exclusion (as here for OpenCover) that would also exclude any methods I add to the type in a `with member` extension; otherwise this requires the adding same sort of meaningless rote unit tests for the compiler code as covering auto-properties does.

**Comment by Bertk** [comment]
The issue might be out-dated because new releases are available.

Please reopen the issue if the bug still exists and can be reproduced with latest preview from [coverlet nightly build](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly).

see [Consume nightly build](https://github.com/coverlet-coverage/coverlet/blob/9295fca754531d6badd0185d0709d41a6eeddd5f/Documentation/ConsumeNightlyBuild.md)
