### ISSUE TITLE
The path is empty. (Parameter 'path')

### ISSUE THREAD

**Issue by Adam-RapidRTC** [coverlet-coverage/coverlet#775]
Having an issue generating the report. The project is SDK format but references older projects. When I run'

(actual paths omitted)
`dotnet test "....csproj" --configuration Release --filter Category!=IntegrationTest --logger:trx --results-directory "...\TestResults" --settings "....runsettings" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="....Tests.cobertura.xml"`

I get the following error

> Calculating coverage result...
>   Generating report '....Tests.cobertura.xml'
> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error : The path is empty. (Parameter 'path') [....Tests.csproj]
> ...nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at System.IO.Path.GetFullPath(String path) [...Tests.csproj]
> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at System.IO.Directory.GetDirectoryRoot(String path) [....Tests.csproj]
> ....nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer) [....Tests.csproj]
> ..\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at System.Linq.GroupedEnumerable`2.GetEnumerator() [...Tests.csproj]
> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList() [...Tests.csproj]
> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.Core.Reporters.CoberturaReporter.Report(CoverageResult result) in D:\git\coverletToRelease\src\coverlet.core\Reporters\CoberturaReporter.cs:line 34 [...Tests.csproj]
> C:\Users\aharris\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.MSbuild.Tasks.ReportWriter.WriteReport() in D:\git\coverletToRelease\src\coverlet.msbuild.tasks\ReportWriter.cs:line 50 [....Tests.csproj]
> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.MSbuild.Tasks.CoverageResultTask.Execute() in D:\git\coverletToRelease\src\coverlet.msbuild.tasks\CoverageResultTask.cs:line 145 [...Tests.csproj]

This works for several other projects in the solution that don't have a reference to older projects. 

I also noticed I get these warnings when building:

> ...\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(7,5): warning : [coverlet] Unable to instrument module: ...Tests\bin\Debug\net472\Microsoft.ReportViewer.Common.dll because : No symbol found for file: ....Tests\bin\Debug\net472\Microsoft.ReportViewer.Common.dll [....Tests.csproj]
> ...\aharris\.nuget\packages\coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets(7,5): warning : [coverlet] Unable to instrument module: ....Tests\bin\Debug\net472\Microsoft.ReportViewer.WebForms.dll because : No symbol found for file: ....Tests\bin\Debug\net472\Microsoft.ReportViewer.WebForms.dll [....Tests.csproj]

**Comment by MarcoRossignoli** [comment]
Hi Adam,

thank's for reporting this, can you try to generate a repro?

@daveMueller seem an issue here https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Reporters/CoberturaReporter.cs#L166 do you have some idea?

> I also noticed I get these warnings when building:

Warnings are ok...we cannot instrument dll without local source so they're expected.

**Comment by MarcoRossignoli** [comment]
@Adam-RapidRTC  despite bug, can you try with collectors you already use runsettings, vstest integration is the better way to consume coverlet at the moment https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by MarcoRossignoli** [comment]
@Adam-RapidRTC can you try to run in debug mode and tell me if the issue is still present?
I found the place of the issue, btw I'd like to understand how it's possible, seem that pdb for some project reports empty path file.
We can fix this particular issue inside report generation, but I'd like to understand why that empty path exists.

Are you able to create a small repro?

**Comment by Adam-RapidRTC** [comment]
@MarcoRossignoli I will see if I can carve out some time today and create a sample repo that recreates the problem.

**Comment by MarcoRossignoli** [comment]
Thanks a lot!

**Comment by daveMueller** [comment]
> @daveMueller seem an issue here https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Reporters/CoberturaReporter.cs#L166 do you have any idea?
> 

Yes seems the ```CoverageResult``` has a ```Document``` with a empty path. I could add a check for this but I'm not sure if the ```CoberturaReporter``` is the right place for this.
I guess the other reporters could also have a problem with such a ```CoverageResult```.
So @Adam-RapidRTC a repro would help a lot to tackle this issue.

**Comment by Adam-RapidRTC** [comment]
@daveMueller @MarcoRossignoli - Sorry for the delay but I'll work on getting that demo repo up for you today.

**Comment by MarcoRossignoli** [comment]
No prob no rush at your pace, thanks.

**Comment by MarcoRossignoli** [comment]
@Adam-RapidRTC any news?

**Comment by NerdBrez** [comment]
Any update about this issue?

**Comment by daveMueller** [comment]
@NerdBrez Are you facing the same issue with cobertura report? Could you create a small repro?

**Comment by NerdBrez** [comment]
Yes, I'm trying to generate a report on my xUnit test. The test project references an .Net framework 4.7.2 web application and performs 8 tests on some MVC controllers. 
The tests pass but then coverlet raises the errors when generating the reports:

**dotnet test lqe.web.test --framework net472 --no-build  /p:CollectCoverage=true  /p:CoverletOutput=../TestResults/Coverage/ /p:MergeWith="../TestResults/Coverage/coverage.json" /p:CoverletOutputFormat=\"cobertura,json\" -m:1**

C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source. [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(31,5): warning : [coverlet] Unable to instrument module: C:\Repos\Lqe\Code\Lqe\lqe.web.test\bin\Debug\Microsoft.Web.Infrastructure.dll because : No symbol found for file: C:\Repos\Lqe\Code\Lqe\lqe.web.test\bin\Debug\Microsoft.Web.Infrastructure.dll [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
Série de tests pour C:\Repos\Lqe\Code\Lqe\lqe.web.test\bin\Debug\Lqe.Web.Test.dll(.NETFramework,Version=v4.7.2)
Outil en ligne de commande d'exécution de tests Microsoft (R), version 16.8.1
Copyright (c) Microsoft Corporation. Tous droits réservés.

Démarrage de l'exécution de tests, patientez...
Au total, 1 fichiers de test ont correspondu au modèle spécifié.

Réussi! - Failed:     0, **Passed:     8**, Skipped:     0, Total:     8, Duration: 1 s- Lqe.Web.Test.dll (net472)

Calculating coverage result...
  Generating report '..\TestResults\Coverage\coverage.cobertura.xml'
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error : **The path is empty**. (Parameter 'path') [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at System.IO.Path.GetFullPath(String path) [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at System.IO.Directory.GetDirectoryRoot(String path) [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer) [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at System.Linq.GroupedEnumerable`2.GetEnumerator() [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList() [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at Coverlet.Core.Reporters.CoberturaReporter.Report(CoverageResult result) in /_/src/coverlet.core/Reporters/CoberturaReporter.cs:line 34 [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at Coverlet.MSbuild.Tasks.ReportWriter.WriteReport() in /_/src/coverlet.msbuild.tasks/ReportWriter.cs:line 50 [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]
C:\Repos\Lqe\Code\Lqe\packages\coverlet.msbuild.2.9.0\build\coverlet.msbuild.targets(60,5): error :    at Coverlet.MSbuild.Tasks.CoverageResultTask.Execute() in /_/src/coverlet.msbuild.tasks/CoverageResultTask.cs:line 148 [C:\Repos\Lqe\Code\Lqe\lqe.web.test\Lqe.Web.Test.csproj]

**Comment by daveMueller** [comment]
Ok thanks. @NerdBrez can you share/attach your project to this issue? Or at least the parts that lead to this issue (maybe the controllers and the tests or so). Otherwise I will try to set up a sample to reproduce this.

**Comment by daveMueller** [comment]
Today I set up an MVC project with 4.7.2 framework and XUnit 2.4.1 unit tests. Unfortunately everything worked without a problem and I couldn't reproduce the issue described above. A small sample project that has the same error would help a lot.

**Comment by NerdBrez** [comment]
Hello, 
My MVC application (C#) have a project reference to a library coded in VB in the same solution.
When I remove it from te coverage with the Exclude parameter, it works fine. No idea why...

**Comment by daveMueller** [comment]
Cool thanks for the info. I will give it a try with a additional VB class library in the solution. I'm currently really busy so it could take a couple of days to test this :pray:.

**Comment by daveMueller** [comment]
The hint with the VB project that @NerdBrez provided was worth its weight. I set up a solution with an MVC project with XUnit and a VB class library project that let me reproduce this error.  Here is the repo  => [https://github.com/daveMueller/coverlet775](url)

![grafik](https://user-images.githubusercontent.com/19378678/105286972-99a80400-5bb7-11eb-864e-281cf5b0d860.png)

Up to now I didn't find the time to debug into this but I will in the next days. Just to let you know that we are still on this. And at least we have a repro now :wink:.

**Comment by daveMueller** [comment]
The issue is the ```My``` namespace in Visual Basic ([My](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/development-with-my/)). Usually a sequence point has a reference to a source file like this.

![grafik](https://user-images.githubusercontent.com/19378678/106076137-3ebe6180-610f-11eb-9370-32cd947c381b.png)

In Visual Basic the compiler injects the ```My``` classes into the assembly without a reference to a source file.

![grafik](https://user-images.githubusercontent.com/19378678/106076878-c193ec00-6110-11eb-9c6b-8446172711de.png)

Maybe there are also other scenarios where a sequence point doesn't have a reference to a source file that we haven't encountered yet. So I created a PR that excludes code like this within an assembly.

**Comment by daveMueller** [comment]
By the way I updated the repro to be a lot smaller than the first implementation ([https://github.com/daveMueller/coverlet775](https://github.com/daveMueller/coverlet775)).

**Comment by sebastianslutzky** [comment]
hi. this issue is still open, but is there a workaround? I am hitting the same problem with an old vb project I converted to sdk style

**Comment by daveMueller** [comment]
Hi @sebastianslutzky, I worked on the PR again and think it fixes the issue. I compiled the source locally and I would be happy if someone could give it try with the packages attached here.
[Packages.zip](https://github.com/coverlet-coverage/coverlet/files/10484539/Packages.zip)

**Comment by TerryChan2** [comment]
Hi @daveMueller, I got the "The path is empty. (Parameter 'path')" when I use coverlet.console 3.2.0 in my test projects. I tried replace the files using your package and the error is gone!.  When this fix will be officially released?
