### ISSUE TITLE
DeterministicBuild fix in nightly build not working

### ISSUE THREAD

**Issue by eduherminio** [coverlet-coverage/coverlet#854]
I don't manage to get code coverage when building with `/p:ContinuousIntegrationBuild=true`.
Installed versions:

- `coverlet.collector v1.3.0-preview-0001-gfa138c0e00`
- `coverlet.msbuild v2.9.0-preview-0001-gfa138c0e00`

## Issue reproduction:

[Sample repo](https://github.com/eduherminio/SheepTools/tree/coverlet-issue) (`coverlet-issue` branch):

Works:
```bash
dotnet clean && dotnet build /p:ContinuousIntegrationBuild=false && dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput=./CoverageResults/"
```

[Azure DevOps build with coverage](https://dev.azure.com/eduherminio/SheepTools/_build/results?buildId=446&view=artifacts&type=publishedArtifacts)

Doesn't work

```bash
dotnet clean && dotnet build /p:ContinuousIntegrationBuild=true  && dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput=./CoverageResults/"
```

[Azure DevOps build without coverage](https://dev.azure.com/eduherminio/SheepTools/_build/results?buildId=447&view=artifacts&type=publishedArtifacts)

**Comment by MarcoRossignoli** [comment]
I don't see in you branch a required file imported in all test projects(current workaround that we'll remove in future asap roslyn will support it).
Take a look at guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/DeterministicBuild.md
And to our sample https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/DeterministicBuild
And better if you use collectors integration instead of msbuild https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md(You can remove `coverlet.msbuild` reference).

**Comment by eduherminio** [comment]
Oh, it was my understanding that the nightly build already contained the fix so that the workaround could be removed.

**Comment by MarcoRossignoli** [comment]
Unfortunately at the moment we need the workaround. Feel free to close if solved!

**Comment by eduherminio** [comment]
Cool, thanks!
