### ISSUE TITLE
Question: [MSTest] Is coverage supported with enabled in-assembly parallel execution

### ISSUE THREAD

**Issue by N-Olbert** [coverlet-coverage/coverlet#864]
MSTest offers the parallel execution of tests within an assembly.

According to their RFC this may cause problems with data collectors:

> Features that rely on data collectors will need to globally turn OFF parallel execution. 
[Source](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/004-In-Assembly-Parallel-Execution.md#notes)

In fact, I know it causes problems with TFS' built in code coverage, but I wonder if this is also the case for coverlet.

In a local test with 40 (parallized) tests I did not encounter any issues, but i wonder if there is any (official) statement about this (f. e. maybe it is impossible for parallism to cause problems by coverlets architecture).

**Comment by MarcoRossignoli** [comment]
The parallel execution of tests should not be a problem from coverlet perspective, xunit test run in parallel by design(one per class), and also by design we run coverage of parallel test projects. The only possible issue could be if same build artifacts (dll inside bin/debug) are used in more than one process at same time, because we gather hits in a file with name embedded inside instrumented dll. So could race. But parallel tests of single run are completely supported, because we save hit in an in memory fixed array with Interlocked increment.

**Comment by N-Olbert** [comment]
@MarcoRossignoli Thanks for clarification 👍
