### ISSUE TITLE
VSTest integration: Is ExcludeByAttribute supported?

### ISSUE THREAD

**Issue by StefanOssendorf** [coverlet-coverage/coverlet#917]
Hey guys,

is the option ExcludeByAttribute supported by the VSTest integreation?
The [documentation](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md) does not list it as supported but the example file below includes the option.

I am asking because I have weird results when using it. When I add `<ExcludeByAttribute>GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>` in my settings file not only code with the attributes get removed but also the coverage ignores complete methods from tested classes without the attributes.
Unfortunately I am not able to reproduce it with a new project and I can't share the code (work) :-/.  

Perhaps I can share the generated cobertura files if that's enough and I get permission to do so.

Thanks in advance

**Comment by MarcoRossignoli** [comment]
Hi @StefanOssendorf sorry for late response I was on vacation.

> is the option ExcludeByAttribute supported by the VSTest integreation?

Yes `ExcludeByAttribute` is supported and we have to update guide. Param ref https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.collector/DataCollection/CoverletSettings.cs#L44


> I am asking because I have weird results when using it. When I add <ExcludeByAttribute>GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute> in my settings file not only code with the attributes get removed but also the coverage ignores complete methods from tested classes without the attributes.

This happens because you cannot use `CompilerGeneratedAttribute` because every `async/await` code you use in your code will be trimmed out because that statements generates a state machine class(Roslyn compiler does it) with that attributes on top of class. So you don't see that code in coverage.

Take a look here https://github.com/coverlet-coverage/coverlet/issues/794#issuecomment-612067552

**Comment by StefanOssendorf** [comment]
Sorry for my way too late response.
Yeah the `CompilerGeneratedAttribute` makes sense. Should have seen that.
Thanks for the link to 497. The skip autoproperties option is awesome. 👍🏻
