### ISSUE TITLE
Does Coverlet ONLY support SDK-style projects

### ISSUE THREAD

**Issue by FortuneN** [coverlet-coverage/coverlet#963]
Is this statement still true?

> Coverlet supports only SDK-style projects https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

I ask because it is specified in the README and yet :

- I've tested with a .Net framework (not sdk style) project and it works (Good job!!!)
- It is said that it _NOW_ works in this issue  (May 13, 2019)  -> https://github.com/coverlet-coverage/coverlet/issues/115

I'm using the cli tool (not sure if this makes any difference)

**Comment by MarcoRossignoli** [comment]
In past we had some issue for some .NET Framework scenario, so if it works in your case ok, but in case of issue related to project style we won't fix to support old style.
So we thought to be "strong" in that statement, also because we'll follow the .NET 5/future roadmap of .NET ecosystem and we'll prioritize .NET "Core" runtimes.

**Comment by MarcoRossignoli** [comment]
Close because answered, feel free to reopen if needed.
