### ISSUE TITLE
Contribution guide?

### ISSUE THREAD

**Issue by ffMathy** [coverlet-coverage/coverlet#975]
I would love to contribute to this library, but I don't know where to start, or how to "debug" my changes. I tried cloning the repo and running tests, but many of the integration tests fail, and I don't know why.

An explainer in the `README.md` would be good.

**Comment by MarcoRossignoli** [comment]
I would love to contribute to this library

Hi @ffMathy! At the moment we don't have a great documentation on how to debug stuff so I try to help here with some guidelines(It was on our roadmap):

We have like every other project a lot of unit testing for every part of the application, btw sometimes to understand why some code is not reported correctly we need to run a sort of "integration" test to debug where is the problem.
To do that we have implemented some "helpers" to simulate a real coverage session. The nature of coverage is pretty invasive because we need to inject new IL instructions to allow to hit accounting. Due to that we have to copy/paste+rename test dll that we'll use for instrumentation of a specific part/pattern of C# code. We do that out of process using a package called `Tmds.ExecFunction`. In this way all instrumentation and accounting will run out of process without any concurrent file access issue.

Clearly we need also to "debug" this tests and to allow that we need to instrument and load "in process" because visual studio debugger need access to file+pdb stuff. In that case we added a simple extension method that will instrument copied dll inprocess during debugging so we can check step-by-step all phases.

Take a look at this first explained example of a complete instrumentation:

https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Coverage/CoverageTests.SelectionStatements.cs#L14

```cs
        public void SelectionStatements_If()
        {
            // We need to pass file name to remote process where it save instrumentation result
            // Similar to msbuild input/output
            string path = Path.GetTempFileName();
            try
            {
                // Lambda will run in a custom process to avoid issue with statics and file locking
                FunctionExecutor.Run(async (string[] pathSerialize) =>
                {
                    // Run load and call a delegate passing class as dynamic to simplify method call
                    CoveragePrepareResult coveragePrepareResult = await TestInstrumentationHelper.Run<SelectionStatements>(instance =>
                    {
                        // We call method to trigger coverage hits
                        instance.If(true);

                        // For now we have only async Run helper
                        return Task.CompletedTask;
                    }, persistPrepareResultToFile: pathSerialize[0]);

                    // we return 0 if we return something different assert fail
                    return 0;
                }, new string[] { path });

                // We retrive and load CoveragePrepareResult and run coverage calculation
                // Similar to msbuild coverage result task
                CoverageResult result = TestInstrumentationHelper.GetCoverageResult(path);

                // Generate html report to check
                // TestInstrumentationHelper.GenerateHtmlReport(result);

                // Asserts on doc/lines/branches
                result.Document("Instrumentation.SelectionStatements.cs")
                      // (line, hits)
                      .AssertLinesCovered((11, 1), (15, 0))
                      // (line,ordinal,hits)
                      .AssertBranchesCovered((9, 0, 1), (9, 1, 0));
            }
            finally
            {
                // Cleanup tmp file
                File.Delete(path);
            }
```

As you can see in this code we use the helper `TestInstrumentationHelper` to instrument particular dll(where the T class resides) and in a lamba we can call every method/props belonging to that class because `instance` is a `dynamic` object type.
To avoid issue with concurrent access we're using `FunctionExecutor.Run` that will run lambda in new process.
At the end of run we can get coverage result and do assertions on real coverage. Also you can generate web reports in automatic way thanks to ReportGenerator integration https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Coverage/InstrumenterHelper.Assertions.cs#L23 (pass true to `show`).

The above code will run test in a new process and will work only running by console `dotnet test` you cannot run inside visual studio.
To debug step-by-step we added some extension method to run all instrumentation/coverage inprocess with visual studio debugged attached 

https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Coverage/InstrumenterHelper.cs#L305

So if you simply change the line 

```cs
  FunctionExecutor.Run(async (string[] pathSerialize) =>
```

with

```cs
 FunctionExecutor.RunInProcess(async (string[] pathSerialize) =>
```

and add a breakpoint [here](https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Coverage/InstrumenterHelper.cs#L120) you can step into engine and debug all from instrumentation to accounting.

If you need further help feel free to DM me on twitter https://twitter.com/MarcoRossignoli (until a good guide will be available, could be a great good start PR 😄  write a debugging guide )

**Comment by Bertk** [comment]
I use this helper script (OS: Windows) which cleans up build artifacts before and create new build output. 

```text
del /s /Q coverage.cobertura.xml
del /s /Q coverage.json
rd /s /q artifacts

rd /s /q "%USERPROFILE%\.nuget\packages\coverlet.msbuild\V1.0.0"
rd /s /q "%USERPROFILE%\.nuget\packages\coverlet.collector\V1.0.0"
for /d /r . %%d in (TestResults bin obj) do @if exist "%%d" rd /s/q "%%d"
for /d /r "%USERPROFILE%\.nuget\packages" %%x in ( "coverlet.msbuild\6.0.3-preview*" "coverlet.collector\6.0.3-preview*" "coverlet.console\6.0.3-preview*" ) do rd /s /q "%%x"

pause 
dotnet pack -c Debug src\coverlet.msbuild.tasks\coverlet.msbuild.tasks.csproj /p:ContinuousIntegrationBuild=true
dotnet pack -c Debug src\coverlet.collector\coverlet.collector.csproj /p:ContinuousIntegrationBuild=true
dotnet build -bl:build.binlog /p:ContinuousIntegrationBuild=true
dotnet pack -c debug /p:ContinuousIntegrationBuild=true
dotnet pack -c release /p:ContinuousIntegrationBuild=true
dotnet build-server shutdown

rem dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[coverlet.collector]*%%2c[coverlet.core]*%%2c[coverlet.msbuild.tasks]*" /p:Exclude="[coverlet.core.tests.samples.netstandard]*%%2c[coverlet.tests.xunit.extensions]*"
rem dotnet test --no-build -bl:test.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[coverlet.core.tests.samples.netstandard]*%%2c[coverlet.tests.xunit.extensions]*%%2c[coverlet.tests.projectsample]*%%2c[testgen_]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --diag:"C:\GitHub\coverlet\artifacts\log\Debug\coverlet.test.diag.log;tracelevel=verbose"

rem dotnet test -c Debug --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

rem reportgenerator -reports:"**/*.opencover.xml" -targetdir:"artifacts\reports" -reporttypes:"HtmlInline_AzurePipelines_Dark;Cobertura" -assemblyfilters:"-xunit;-coverlet.testsubject;-Coverlet.Tests.ProjectSample.*;-coverlet.core.tests.samples.netstandard;-coverlet.tests.utils;-coverlet.tests.xunit.extensions;-coverletsamplelib.integration.template" 

```
